services:
  backend:
    command: npm run dev

  proxy:
    volumes:
      - ./proxy:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: builder
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5274:5173"
    command: npm run dev -- --host

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    networks:
      - sandbox-net
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 8g
    restart: unless-stopped

  suggestions:
    build:
      context: ./auto-complete
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    networks:
      - sandbox-net
    environment:
      - OLLAMA_HOST=https://ollama.com
